### ISSUE TITLE
Compilation fails if signatures file isn't found

### ISSUE THREAD

**Issue by Werkov** [fykosak/fks-texmf#45]
This makes local compilations troublesome if there's no make/Git in place (and one wants to use proper signatures in metadata).

Suggestion: print a warning and make compilation succeed (possibly with a placeholder instead of signature).

**Comment by Headary** [comment]
On the other hand, this also serves as a protection against incorrectly inputed signatures. And at this point, most of the people use Astrid for compilation, and if they wanted local compilation, they would need make regardless. And accorging to `fkssignature`, if the file is not found, it just gives of warning and than failes on the missing signature, which could be fixed by creating the signature manually in the worst case.
